isao.photorate.db.**
isao.photorate.galleryUi.**
isao.photorate.galleryRepository.**

kotlin.collections.List<*>
kotlin.collections.Set<*>
kotlin.collections.Map

//TODO add other generated and manually created data classes