isao.photorate.gallery.db.**
isao.photorate.galleryComponent.db.**
isao.photorate.config.db.**
isao.photorate.search.db.**
isao.photorate.app.db.**
isao.photorate.galleryUi.**
isao.photorate.searchUi.**
isao.photorate.configUi.**
isao.photorate.homeUi.**
isao.photorate.galleryComponent.data.**

kotlin.collections.List<*>
kotlin.collections.Set<*>
kotlin.collections.Map

//TODO add other generated and manually created data classes
