package isao.photorate.coreUi.icon

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/** Placeholder intrinsic size: the details screen sizes the image from the painter. */
private val BROKEN_IMAGE_SIZE = 160.dp

/**
 * Generated by the Material Symbols renderer:
 * https://fonts.gstatic.com/render/v1/Material+Symbols+Outlined/24dp/broken_image.kt?var=opsz,wght,FILL,GRAD,ROND@24,400,1,0,50
 */
@Suppress("CheckReturnValue")
internal fun broken_image(
  tint: Color,
  width: Dp = BROKEN_IMAGE_SIZE,
  height: Dp = BROKEN_IMAGE_SIZE,
): ImageVector =
  ImageVector.Builder(
      name = "broken_image",
      defaultWidth = width,
      defaultHeight = height,
      viewportWidth = 24f,
      viewportHeight = 24f,
    )
    .apply {
      path(
        fill = SolidColor(tint),
        fillAlpha = 1f,
        stroke = null,
        strokeAlpha = 1f,
        strokeLineWidth = 1f,
        strokeLineCap = StrokeCap.Butt,
        strokeLineJoin = StrokeJoin.Bevel,
        strokeLineMiter = 1f,
        pathFillType = PathFillType.Companion.NonZero,
      ) {
        moveTo(5f, 21f)
        quadTo(4.18f, 21f, 3.59f, 20.41f)
        reflectiveQuadTo(3f, 19f)
        verticalLineTo(12.4f)
        lineToRelative(3f, 3f)
        lineToRelative(4f, -4f)
        lineToRelative(4f, 4f)
        lineToRelative(4f, -4f)
        lineToRelative(3f, 3f)
        verticalLineTo(19f)
        quadToRelative(0f, 0.82f, -0.59f, 1.41f)
        reflectiveQuadTo(19f, 21f)
        horizontalLineTo(5f)
        close()
        moveTo(5f, 3f)
        horizontalLineTo(19f)
        quadToRelative(0.83f, 0f, 1.41f, 0.59f)
        reflectiveQuadTo(21f, 5f)
        verticalLineToRelative(6.57f)
        lineToRelative(-3f, -3f)
        lineToRelative(-4f, 4f)
        lineToRelative(-4f, -4f)
        lineToRelative(-4f, 4f)
        lineToRelative(-3f, -3f)
        verticalLineTo(5f)
        quadTo(3f, 4.17f, 3.59f, 3.59f)
        reflectiveQuadTo(5f, 3f)
        close()
      }
    }
    .build()
