package isao.photorate.android

import android.content.Context
import android.opengl.EGL14
import android.opengl.EGLConfig
import android.opengl.EGLContext
import android.opengl.EGLDisplay
import android.opengl.EGLSurface
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.google.ai.edge.litert.Accelerator
import com.google.ai.edge.litert.CompiledModel
import com.google.ai.edge.litert.Environment
import com.google.ai.edge.litert.LiteRtException
import isao.photorate.imageRecognition.litert.CompiledModelRunner
import isao.photorate.imageRecognition.litert.LiteRtRtmModels
import isao.photorate.imageRecognition.litert.MathOps
import java.io.InputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.abs
import kotlin.math.max
import kotlin.math.min
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

// TODO cleanup? Not useful for day-to-day testing.
/**
 * On-device verification of the LiteRT-converted RTM hand models (see the ml/litert/ model recipe
 * and the on-device-verification skill).
 *
 * For each model, on each accelerator (CPU control, then strict GPU):
 * - GPU residency: a strict `Accelerator.GPU` compile succeeds (no CPU fallback is possible in
 *   CompiledModel — failure names the op).
 * - Numeric parity vs the host-dumped ONNX references (correlation + max abs diff on every output).
 * - Task gate: detector NMS box set must match the reference set (count + max box diff); pose
 *   decoded keypoints must stay within a few px of the reference.
 * - Latency: warmup once (shader compile), then 10 timed run+readback inferences, reporting
 *   median/mean.
 *
 * References are in ml/litert/refs (generated by dump_refs.py from the f32clean ONNX models) and
 * are packaged as test assets. Every result row is logged with the `LITERT` tag for
 * machine-parseable collection.
 *
 * GPU buffers: the GL accelerator's managed IO buffers default to GL textures, whose allocation
 * requires a *current* EGL context (litert's GlTexture wraps the TFLite GL delegate's GlTexture,
 * which calls glGenTextures on whatever context is current). Instrumentation tests have no GL
 * context by default, so every GPU path in this file runs inside an [EglEnv] scope.
 */
@RunWith(AndroidJUnit4::class)
class LiteRtOnDeviceVerificationTest {

  private val context: Context = ApplicationProvider.getApplicationContext()
  private val assets = InstrumentationRegistry.getInstrumentation().context.assets

  // Optional instrumentation args:
  //   gpuBackend: "OPENCL" / "OPENGL" / "WEBGPU" to force a GPU backend
  //   gpuPrecision: "FP16" / "FP32" / "DEFAULT" (default: FP32 — the GPU
  //     delegate's fp16 reductions drift by ~1e-2 and can flip a marginal
  //     NMS box; FP32 keeps the box set identical to CPU at nearly the same
  //     GPU latency, so it is the accuracy-safe default here).
  private val gpuBackend: CompiledModel.GpuOptions.Backend? =
    InstrumentationRegistry.getArguments().getString("gpuBackend")?.let {
      CompiledModel.GpuOptions.Backend.valueOf(it)
    }
  private val gpuPrecision: CompiledModel.GpuOptions.Precision? =
    InstrumentationRegistry.getArguments().getString("gpuPrecision")?.let {
      CompiledModel.GpuOptions.Precision.valueOf(it)
    } ?: CompiledModel.GpuOptions.Precision.FP32

  @Test
  fun verifyDetectorOnGpuAndCpu() {
    verifyModel(
      asset = LiteRtRtmModels.DETECTOR_ASSET,
      tags = listOf("rand", "real"),
      inputRef = { tag -> "det_${tag}_input.npy" },
      gates = detGates,
      taskGate = ::detectorTaskGate,
    )
  }

  /**
   * Detector task gate: the NMS-kept box set must match the reference set order-independently (a
   * ~1e-5 score tie can flip anchor order between runtimes, so pairwise index comparison is too
   * brittle). Every reference box must have a device box with IoU > 0.5.
   */
  private fun detectorTaskGate(
    runner: CompiledModelRunner,
    tag: String,
  ): TaskResult {
    val boxes = runner.readOutput(0)
    val scores = runner.readOutput(1)
    val keep = LiteRtRtmModels.nmsAnchors(boxes, scores)
    val ref = readRefF32("det_${tag}_refboxes.npy")
    val refCount = ref.size / 5
    var matched = 0
    var minMatchIou = 1f
    val used = BooleanArray(keep.size)
    for (r in 0 until refCount) {
      val rx1 = ref[r * 5]
      val ry1 = ref[r * 5 + 1]
      val rx2 = ref[r * 5 + 2]
      val ry2 = ref[r * 5 + 3]
      var bestIou = 0f
      var bestIdx = -1
      for (k in keep.indices) {
        if (used[k]) continue
        val o = keep[k] * 4
        val iou =
          MathOps.iou(
            rx1,
            ry1,
            rx2,
            ry2,
            boxes[o],
            boxes[o + 1],
            boxes[o + 2],
            boxes[o + 3],
          )
        if (iou > bestIou) {
          bestIou = iou
          bestIdx = k
        }
      }
      if (bestIou > 0.5f) {
        used[bestIdx] = true
        matched++
        minMatchIou =
          min(
            minMatchIou,
            bestIou,
          )
      }
    }
    log(
      "det_${tag}_nms_keep=${keep.size} ref_keep=$refCount matched=$matched min_match_iou=$minMatchIou"
    )
    return TaskResult(
      matched == refCount,
      "det $tag $matched/$refCount boxes matched",
    )
  }

  @Test
  fun verifyPoseOnGpuAndCpu() {
    verifyModel(
      asset = LiteRtRtmModels.RTMPOSE_ASSET,
      tags = listOf("rand", "real"),
      inputRef = { tag -> "pose_${tag}_input.npy" },
      gates = poseGates,
      taskGate = ::poseTaskGate,
    )
  }

  /**
   * Pose task gate: decoded keypoints must match the reference (argmax bins over 512, split ratio
   * 2.0).
   */
  private fun poseTaskGate(
    runner: CompiledModelRunner,
    tag: String,
  ): TaskResult {
    val kps =
      LiteRtRtmModels.decodeSimcc(
        runner.readOutput(0),
        runner.readOutput(1),
      )
    val ref = readRefF32("pose_${tag}_kps.npy")
    var maxPx = 0f
    for (i in 0 until 21) {
      maxPx =
        max(
          maxPx,
          abs(kps[i * 3] - ref[i * 3]),
        )
      maxPx =
        max(
          maxPx,
          abs(kps[i * 3 + 1] - ref[i * 3 + 1]),
        )
    }
    log("pose_${tag}_kp_max_px_diff=$maxPx")
    return TaskResult(
      maxPx < 3f,
      "pose $tag keypoints ok ($maxPx px)",
    )
  }

  /**
   * Quantized variants of the two shipped models (accuracy-safe-quantization skill): fp16
   * float-casting and dynamic-range int8, generated by ml/litert/scripts/quantize_models.py and
   * packaged as app assets.
   *
   * fp16 (weights fp16, compute fp32, op set unchanged) is the candidate quality row — same strict
   * GPU residency + parity + task gates as the float32 baseline. int8 is measured the same way, but
   * per the skill its host-CPU numbers are pessimistic and the task gate is the verdict; an int8
   * miss is logged as a finding, not a shipping blocker (fp16 is the shrink that ships if int8
   * degrades).
   */
  @Test
  fun verifyQuantizedVariants() {
    verifyQuantizedVariant(
      asset = "rtmdet_hand_320_f16.tflite",
      prefix = "det",
      gates = detGates,
      taskGate = ::detectorTaskGate,
      requireGpuCompile = true,
      assertTaskGate = true,
    )
    verifyQuantizedVariant(
      asset = "rtmdet_hand_320_i8.tflite",
      prefix = "det",
      gates = detGates,
      taskGate = ::detectorTaskGate,
      requireGpuCompile = false,
      assertTaskGate = false,
    )
    verifyQuantizedVariant(
      asset = "rtmpose_hand_256_f16.tflite",
      prefix = "pose",
      gates = poseGates,
      taskGate = ::poseTaskGate,
      requireGpuCompile = true,
      assertTaskGate = true,
    )
    verifyQuantizedVariant(
      asset = "rtmpose_hand_256_i8.tflite",
      prefix = "pose",
      gates = poseGates,
      taskGate = ::poseTaskGate,
      requireGpuCompile = false,
      assertTaskGate = false,
    )
  }

  private fun verifyQuantizedVariant(
    asset: String,
    prefix: String,
    gates: List<Gate>,
    taskGate: (CompiledModelRunner, String) -> TaskResult,
    requireGpuCompile: Boolean,
    assertTaskGate: Boolean,
  ) {
    log("quantized_variant_asset=$asset")
    verifyModel(
      asset = asset,
      tags = listOf("rand", "real"),
      inputRef = { tag -> "${prefix}_${tag}_input.npy" },
      gates = gates,
      taskGate = taskGate,
      // int8 corr is log-only — the
      // task gate is the verdict
      // (host CPU
      // int kernels are
      // pessimistically worse than
      // the device GPU).
      corrMin = if (assertTaskGate) 0.95f else 0f,
      requireGpuCompile = requireGpuCompile,
      assertTaskGate = assertTaskGate,
    )
  }

  /**
   * Micro-probe of the GPU delegate's supported op set (on-device-verification skill): every op
   * used by the two RTM models, as a ~1KB single-op model, compiled+run under several accelerator
   * configs. Logs SUPPORTED / NOT_SUPPORTED per op per config. Probes are generated by
   * ml/litert/scripts/probe_ops.py.
   *
   * NOTE: the app manifest declares <uses-native-library> for libvndksupport.so and libOpenCL.so —
   * without those, the ClGl accelerator cannot dlopen the vendor OpenCL runtime, silently falls
   * back to GL, and fails at buffer creation. The probe results below were collected with the fix
   * in place.
   */
  @Test
  fun gpuOpSupportProbe() {
    val probes =
      listOf(
        "CONV_2D",
        "DEPTHWISE_CONV_2D",
        "FULLY_CONNECTED",
        "ADD",
        "MUL",
        "SUB",
        "DIV",
        "MAXIMUM",
        "MINIMUM",
        "LOGISTIC",
        "RELU",
        "RELU6",
        "RELU_0_TO_1",
        "CONCATENATION",
        "RESHAPE",
        "TRANSPOSE",
        "PAD",
        "MEAN",
        "SUM",
        "SQRT",
        "GATHER",
        "SPLIT_V",
        "BATCH_MATMUL",
        "SOFTMAX",
        "MAX_POOL_2D",
        "AVERAGE_POOL_2D",
        "RESIZE_NEAREST_NEIGHBOR",
        "RESIZE_BILINEAR",
        "STRIDED_SLICE",
        "SLICE",
        "SQUEEZE",
        // MobileCLIP-S1 combined tflite ops (added for the CLIP GPU check).
        "GELU",
        "RSQRT",
        "SQUARED_DIFFERENCE",
        // Rest
        // of
        // the
        // S1 op
        // inventory (completeness sweep): ABS (f32),
        // CAST
        // (int64->int32 token ids) and EMBEDDING_LOOKUP (int32 ids).
        "ABS",
        "CAST",
        "EMBEDDING_LOOKUP",
      )
    val gpuOpenCl =
      CompiledModel.Options(Accelerator.GPU).apply {
        gpuOptions = CompiledModel.GpuOptions(backend = CompiledModel.GpuOptions.Backend.OPENCL)
      }
    val gpuTex2d =
      CompiledModel.Options(Accelerator.GPU).apply {
        gpuOptions =
          CompiledModel.GpuOptions(
            bufferStorageType = CompiledModel.GpuOptions.BufferStorageType.TEXTURE_2D
          )
      }
    val gpuExternal =
      CompiledModel.Options(Accelerator.GPU).apply {
        gpuOptions =
          CompiledModel.GpuOptions(
            externalTensorsMode = true,
            externalTensorPattern = "*",
          )
      }
    val configs =
      listOf(
        "GPU" to CompiledModel.Options(Accelerator.GPU),
        "CPU_GPU" to
          CompiledModel.Options(
            Accelerator.CPU,
            Accelerator.GPU,
          ),
        "GPU_OPENCL" to gpuOpenCl,
        "GPU_TEX2D" to gpuTex2d,
        "GPU_EXT" to gpuExternal,
      )
    // Probes are packaged with the TEST apk (androidTest
    // assets), so read
    // them from the instrumentation context, not the app
    // context.
    val testContext = InstrumentationRegistry.getInstrumentation().context
    withEgl {
      for ((tag, options) in configs) {
        for (name in probes) {
          val result =
            try {
              CompiledModel.create(
                  testContext.assets,
                  "$name.tflite",
                  options,
                  null,
                )
                .use { model ->
                  // The accelerator(s) declare which buffer types the IO
                  // tensors accept — log them so the buffer strategy is
                  // evidence-driven, not guessed.
                  val req =
                    try {
                      model.getInputBufferRequirements("x").supportedTypes.joinToString(",") {
                        it.name
                      }
                    } catch (e: LiteRtException) {
                      "ERR:${e.message?.take(120)}"
                    }
                  log("probe_${name}_${tag}_req=$req")
                  val ins = model.createInputBuffers()
                  val outs = model.createOutputBuffers()
                  try {
                    // Dtypes must stay in sync with probe_ops.py:
                    // CAST is int64->int32, EMBEDDING_LOOKUP takes
                    // int32 ids (f32 output); every other probe is f32.
                    when (name) {
                      "CAST" -> ins[0].writeLong(LongArray(ins[0].readLong().size))
                      "EMBEDDING_LOOKUP" -> ins[0].writeInt(IntArray(ins[0].readInt().size))
                      else -> ins[0].writeFloat(FloatArray(ins[0].readFloat().size))
                    }
                    model.run(
                      ins,
                      outs,
                    )
                    // CAST outputs int32; every other probe outputs f32.
                    if (name == "CAST") outs[0].readInt() else outs[0].readFloat()
                    "SUPPORTED"
                  } finally {
                    ins.forEach { it.close() }
                    outs.forEach { it.close() }
                  }
                }
            } catch (e: LiteRtException) {
              "NOT_SUPPORTED: ${e.message?.take(400)}"
            }
          log("probe_${name}_$tag=$result")
        }
      }
    }
  }

  /**
   * The same treatment attempted on the *original* in-graph-NMS detector (`end2end.onnx` ->
   * `rtmdet_hand_320_end2end_f32.tflite`), to document why the head-cut `_f32clean` variant is the
   * GPU-clean one: NMS/TOPK and data-dependent Gathers have no GPU kernels, and onnx2tf caps the
   * dynamic NMS output at 5 detections while the source ONNX keeps 39/53 on the two ref inputs. Not
   * a gate — this model is not shipped; the log rows are the finding. The pose `end2end.onnx` is
   * not covered: its dynamic batch dims make onnx2tf fail outright (shape inference error on
   * `Mul_235`).
   */
  @Test
  fun originalDetectorGpuAttempt() {
    val asset = "rtmdet_hand_320_end2end_f32.tflite"
    withEgl {
      // 1) Strict GPU compile —
      // expected to fail on
      // NON_MAX_SUPPRESSION_V4 /
      //    TOPK_V2 / data-dependent
      // GATHER / RELU_0_TO_1.
      try {
        CompiledModelRunner.fromAssets(
            context,
            asset,
            CompiledModel.Options(Accelerator.GPU),
          )
          .use { log("original_det_gpu=COMPILED (unexpected)") }
      } catch (e: LiteRtException) {
        log("original_det_gpu=COMPILE_FAILED: ${e.message?.take(120)}")
      }
      // 2) CPU run: the 5 capped
      // detections must match the
      // ONNX top-5, and
      //    report the CPU latency
      // baseline.
      CompiledModelRunner.fromAssets(
          context,
          asset,
          CompiledModel.Options(Accelerator.CPU),
        )
        .use { runner ->
          runTimed(
            runner,
            "det_real_input.npy",
          ) // warmup
          runner.writeInput(
            0,
            readRefF32("det_real_input.npy"),
          )
          runner.run()
          val dets = runner.readOutput(0)
          val ref = readRefF32("det_real_end2end_dets.npy")
          val refRows = ref.size / 5
          val rows = dets.size / 5
          var maxDiff = 0f
          for (i in
            0 until
              min(
                dets.size,
                ref.size,
              )) {
            maxDiff =
              max(
                maxDiff,
                abs(dets[i] - ref[i]),
              )
          }
          log("original_det_cpu out_rows=$rows ref_rows=$refRows max_diff_vs_onnx_top5=$maxDiff")
          val timing =
            (0 until 10)
              .map {
                runTimed(
                  runner,
                  "det_real_input.npy",
                )
              }
              .sorted()
          log("original_det_cpu latency_median_ms=${timing[timing.size / 2]}")
        }
    }
  }

  // --- shared harness -----------------------------------------------------

  private data class Gate(val name: String, val ref: (String) -> String)

  private data class TaskResult(val ok: Boolean, val msg: String)

  private val detGates =
    listOf(
      Gate("boxes") { tag -> "det_${tag}_boxes.npy" },
      Gate("scores") { tag -> "det_${tag}_scores.npy" },
    )
  private val poseGates =
    listOf(
      Gate("simcc_x") { tag -> "pose_${tag}_simcc_x.npy" },
      Gate("simcc_y") { tag -> "pose_${tag}_simcc_y.npy" },
    )

  /**
   * Runs one model on CPU then strict GPU: loads the fixed inputs, checks numeric parity on every
   * output, runs the model-specific task gate, and benchmarks run+readback after a warmup.
   *
   * Quantized-variant knobs (see [verifyQuantizedVariant]): [corrMin] lowers the correlation floor
   * (int8 corr is log-only), [requireGpuCompile] downgrades a strict-GPU compile failure to a
   * logged finding, and [assertTaskGate] downgrades a task-gate miss to a logged finding.
   */
  private fun verifyModel(
    asset: String,
    tags: List<String>,
    inputRef: (String) -> String,
    gates: List<Gate>,
    taskGate: (CompiledModelRunner, String) -> TaskResult,
    corrMin: Float = 0.99f,
    requireGpuCompile: Boolean = true,
    assertTaskGate: Boolean = true,
  ) {
    val available: Set<Accelerator> =
      try {
        Environment.create().let { env ->
          try {
            env.getAvailableAccelerators()
          } finally {
            env.close()
          }
        }
      } catch (e: LiteRtException) {
        emptySet()
      }
    log("available_accelerators=$available")
    val gpuSupported = available.contains(Accelerator.GPU)
    log("gpu_supported=$gpuSupported")
    assertTrue(
      "device reports no GPU accelerator",
      gpuSupported,
    )

    // GPU (GL) IO buffers need a current EGL context —
    // hold one for the
    // whole CPU+GPU loop (harmless for the CPU pass).
    withEgl {
      for (accel in
        listOf(
          Accelerator.CPU,
          Accelerator.GPU,
        )) {
        val runner =
          try {
            val options = CompiledModel.Options(accel)
            if (accel == Accelerator.GPU) {
              options.gpuOptions =
                CompiledModel.GpuOptions(
                  backend = gpuBackend ?: CompiledModel.GpuOptions.Backend.OPENCL,
                  precision = gpuPrecision,
                )
            }
            CompiledModelRunner.fromAssets(
              context,
              asset,
              options,
            )
          } catch (e: LiteRtException) {
            log("compile_failed accel=$accel err=${e.message?.take(300)}")
            if (accel == Accelerator.GPU && !requireGpuCompile) {
              log("$asset gpu=COMPILE_FAILED (documented, not a gate)")
              continue
            }
            assertTrue(
              "strict $accel compile failed for $asset: ${e.message}",
              accel != Accelerator.GPU,
            )
            continue
          }
        runner.use {
          // Warmup: first GPU inference includes shader compilation.
          runTimed(
            runner,
            inputRef(tags.first()),
          )
          // Numeric parity on every output, every tag. Each gate's ref is
          // matched to the corresponding model output by index.
          val outputs = tags.associateWith { tag ->
            runModel(
              runner,
              inputRef(tag),
            )
          }
          for (tag in tags) {
            val actualAll = outputs.getValue(tag)
            gates.forEachIndexed { i, gate ->
              val ref = readRefF32(gate.ref(tag))
              val corr =
                correlation(
                  actualAll[i],
                  ref,
                )
              val diff =
                maxAbsDiff(
                  actualAll[i],
                  ref,
                )
              log("${gate.name}_${tag}_accel=$accel corr=$corr max_abs_diff=$diff")
              assertTrue(
                "${gate.name} $tag on $accel lost correlation: $corr",
                corr > corrMin,
              )
            }
          }
          // Task gate on the real input (a real image is the honest check).
          val gateResult =
            taskGate(
              runner,
              "real",
            )
          if (assertTaskGate) {
            assertTrue(
              "task gate failed on $accel: ${gateResult.msg}",
              gateResult.ok,
            )
          } else {
            log("task_gate accel=$accel verdict=${gateResult.msg} (documented, not a gate)")
          }
          // Latency: run + readback, after warmup.
          val timings =
            (0 until LATENCY_RUNS).map {
              runTimed(
                runner,
                inputRef(tags.first()),
              )
            }
          val median = timings.sorted()[timings.size / 2]
          val mean = timings.average()
          log(
            "latency asset=$asset accel=$accel runs=${
              timings.joinToString(
                ","
              )
            } median_ms=$median mean_ms=${"%.1f".format(mean)}"
          )
        }
      }
    }
  }

  private fun runModel(
    runner: CompiledModelRunner,
    inputRef: String,
  ): List<FloatArray> {
    runner.writeInput(0, readRefF32(inputRef))
    runner.run()
    return (0 until runner.outputBuffers.size).map { runner.readOutput(it) }
  }

  private fun runTimed(runner: CompiledModelRunner, inputRef: String): Long {
    runner.writeInput(0, readRefF32(inputRef))
    val start = System.nanoTime()
    runner.run()
    runner.readOutput(0) // readback is the sync point — benchmark
    // run+readback together
    return (System.nanoTime() - start) / 1_000_000
  }

  /** Runs [block] with a current EGL context (required by the GL accelerator's IO buffers). */
  private fun <T> withEgl(block: () -> T): T {
    val egl = EglEnv()
    try {
      return block()
    } finally {
      egl.release()
    }
  }

  /**
   * Minimal offscreen EGL environment: display + ES2 context + 1x1 pbuffer surface made current.
   * Enough for glGenTextures / glTexSubImage2D used by litert's GL tensor buffers.
   */
  private class EglEnv {
    private val display: EGLDisplay
    private val context: EGLContext
    private val surface: EGLSurface

    init {
      display = EGL14.eglGetDisplay(EGL14.EGL_DEFAULT_DISPLAY)
      check(display != EGL14.EGL_NO_DISPLAY) { "eglGetDisplay failed" }
      val major = IntArray(1)
      val minor = IntArray(1)
      check(
        EGL14.eglInitialize(
          display,
          major,
          0,
          minor,
          0,
        )
      ) {
        "eglInitialize failed"
      }
      val configs = arrayOfNulls<EGLConfig>(1)
      val numConfigs = IntArray(1)
      // GL shader storage buffers
      // (litert's GlBuffer IO) need
      // ES 3.1+.
      // EGL14 lacks
      // EGL_OPENGL_ES3_BIT; its
      // value is 0x0040
      // (EGL_KHR_create_context).
      val configAttrs =
        intArrayOf(
          EGL14.EGL_SURFACE_TYPE,
          EGL14.EGL_PBUFFER_BIT,
          EGL14.EGL_RENDERABLE_TYPE,
          0x0040, // EGL_OPENGL_ES3_BIT
          EGL14.EGL_NONE,
        )
      check(
        EGL14.eglChooseConfig(
          display,
          configAttrs,
          0,
          configs,
          0,
          configs.size,
          numConfigs,
          0,
        ) && numConfigs[0] > 0
      ) {
        "eglChooseConfig failed"
      }
      val contextAttrs =
        intArrayOf(
          EGL14.EGL_CONTEXT_CLIENT_VERSION,
          3,
          EGL14.EGL_NONE,
        )
      context =
        EGL14.eglCreateContext(
          display,
          configs[0],
          EGL14.EGL_NO_CONTEXT,
          contextAttrs,
          0,
        )
      check(context != EGL14.EGL_NO_CONTEXT) { "eglCreateContext failed" }
      val surfaceAttrs =
        intArrayOf(
          EGL14.EGL_WIDTH,
          1,
          EGL14.EGL_HEIGHT,
          1,
          EGL14.EGL_NONE,
        )
      surface =
        EGL14.eglCreatePbufferSurface(
          display,
          configs[0],
          surfaceAttrs,
          0,
        )
      check(surface != EGL14.EGL_NO_SURFACE) { "eglCreatePbufferSurface failed" }
      check(
        EGL14.eglMakeCurrent(
          display,
          surface,
          surface,
          context,
        )
      ) {
        "eglMakeCurrent failed"
      }
    }

    fun release() {
      EGL14.eglMakeCurrent(
        display,
        EGL14.EGL_NO_SURFACE,
        EGL14.EGL_NO_SURFACE,
        EGL14.EGL_NO_CONTEXT,
      )
      EGL14.eglDestroySurface(
        display,
        surface,
      )
      EGL14.eglDestroyContext(
        display,
        context,
      )
      EGL14.eglTerminate(display)
    }
  }

  // --- reference npy loading ----------------------------------------------

  private fun readRefF32(name: String): FloatArray {
    // The refs dir is added to the androidTest assets by
    // CONTENT (flat), so
    // the npy files sit at the assets root, not under
    // ml/litert/refs/.
    assets.open(name).use { input: InputStream ->
      val bytes = input.readBytes()
      val (_, dataOffset) = parseNpyHeader(bytes)
      val count = (bytes.size - dataOffset) / 4
      val buffer =
        ByteBuffer.wrap(
            bytes,
            dataOffset,
            count * 4,
          )
          .order(ByteOrder.LITTLE_ENDIAN)
      val out = FloatArray(count)
      buffer.asFloatBuffer().get(out)
      return out
    }
  }

  /** Parses a numpy v1.0 .npy header; returns (shape, dataOffset). */
  private fun parseNpyHeader(bytes: ByteArray): Pair<IntArray, Int> {
    require(bytes.size > 10 && bytes[0] == 0x93.toByte() && bytes[1] == 'N'.code.toByte()) {
      "not a numpy file"
    }
    val headerLen = (bytes[8].toInt() and 0xFF) or ((bytes[9].toInt() and 0xFF) shl 8)
    val header =
      String(
        bytes,
        10,
        headerLen,
        Charsets.US_ASCII,
      )
    val shapeMatch =
      Regex("'shape':\\s*\\(([^)]*)\\)").find(header)
        ?: Regex("\"shape\":\\s*\\(([^)]*)\\)").find(header)
    require(shapeMatch != null) { "shape not found in header: $header" }
    val dims =
      shapeMatch.groupValues[1]
        .split(",")
        .map { it.trim() }
        .filter { it.isNotEmpty() && it != "1" && it != "0" }
        .map { it.toInt() }
    return dims.toIntArray() to (10 + headerLen)
  }

  // --- stats ---------------------------------------------------------------

  private fun correlation(a: FloatArray, b: FloatArray): Float {
    var meanA = 0f
    var meanB = 0f
    for (i in a.indices) {
      meanA += a[i]
      meanB += b[i]
    }
    meanA /= a.size
    meanB /= a.size
    var cov = 0.0
    var varA = 0.0
    var varB = 0.0
    for (i in a.indices) {
      val da = a[i] - meanA
      val db = b[i] - meanB
      cov += da * db
      varA += da * da
      varB += db * db
    }
    if (varA == 0.0 && varB == 0.0) return 1f
    return (cov / (kotlin.math.sqrt(varA) * kotlin.math.sqrt(varB))).toFloat()
  }

  private fun maxAbsDiff(a: FloatArray, b: FloatArray): Float {
    var worst = 0f
    for (i in a.indices) {
      worst =
        max(
          worst,
          abs(a[i] - b[i]),
        )
    }
    return worst
  }

  private fun log(msg: String) {
    android.util.Log.i("LiteRtVerify", "LITERT|$msg")
  }

  companion object {
    private const val LATENCY_RUNS = 10
  }
}
